spring.application.name=backend

spring.datasource.url=jdbc:mysql://localhost:3306/ngo_system
spring.datasource.username=ngo_user
spring.datasource.password=password123

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

server.port=8081

jwt.secret=${JWT_SECRET:CHANGE_THIS_TO_LONG_RANDOM_SECRET_KEY_256_BITS_MINIMUM}
jwt.expiration=900000

# Signzy Configuration
signzy.base-url=https://sandbox.signzy.app
signzy.api-key=YOUR_SANDBOX_API_KEY
signzy.client-id=YOUR_CLIENT_ID
signzy.client-secret=YOUR_CLIENT_SECRET


crypto.secret=${CRYPTO_SECRET:CHANGE_THIS_TO_32_BYTE_SECRET_KEY_123456}

blockchain.rpc-url=https://polygon-amoy.infura.io/v3/YOUR_KEY
blockchain.contract-address=0xYourContractAddress
blockchain.admin-private-key=ADMIN_PRIVATE_KEY_ONLY_FOR_SERVER_SIGNING_IF_NEEDED


ipfs.api-url=http://127.0.0.1:5001
ipfs.gateway-url=http://127.0.0.1:8080

blockchain.enabled=false
signzy.enabled=false